server:
  port: 80

spring:
  ai:
    openai:
      api-key: ${AZURE_KEYVAULT_OPENAI_KEY}

azure:
  application-insights:
    instrumentation-key: ${AZURE_APP_INSIGHTS_KEY}
logging:
  level:
    root: INFO
    com.agilesolutions.chatbot: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true